{% set name = "html-proofer" %}
{% set version = "3.12.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 1e5249e3eb3887be985f1a6f63ad915bc12588457c87605f1f7362ba1f646c76

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-addressable >=2.3,<3
    - rb-mercenary >=0.3,<1
    - rb-nokogiri >=1.10,<2
    - rb-parallel >=1.3,<2
    - rb-rainbow >=3.0,<4
    - rb-timerizer >=0.3,<1
    - rb-typhoeus >=1.3,<2
    - rb-yell >=2.0,<3

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Test your rendered HTML files to make sure they're accurate.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/gjtorikian/{{ name }}

extra:
  recipe-maintainers:
    - bgruening
    - sodre
