travis:
  secure:
    BINSTAR_TOKEN: hzA2iF0eMcx7zltjERT6w6gddHaXEsdrh1ZmBYVUTSKQfncbI2NEoGV/oEbMtQc/iLDHpbrhz3A9Ew9DM9wm4dbzEJvcy+PYlHmwx+MUI4wcMglVBMvM6y5sA2Fgqdt39RLP/+JTA9Zly32PcmMufQ2BqK2Dw0kdjv8vaDO2oblyf/GALy2b+PGKTlX+IDpgcgs7iLHmXiTwFHApi+BHjkqcHfoM+gnsZe+yNErErybMkT741DUfuJU3rG3giwR7SjJ4039Bs+0wKaqdSqM+rBHK0QIoqduhn9UVd8p7uqaMRbfnYU44ZhdL7UEaJC3BUaZ6fjux88ymyrptlfGuvlcj9Bo5l2sylVwasWyjz6bo/wjTZGB9cFCAVmAhaJZzQKMFmWhBLEMLrzEAWvF/T2gLjn/TWS0QmbG+gjFOfUFlDfog5ftQj2SaY+h4NjgYnHj09VMDX2JWnRVoHYAbljvRML4cLyack6CyhXBbKele2iO9/oZLdNmJTCnie6R4+L31PjRKCriWBj9l6/2WK2WJiPb7M88Mh0CD5mVqLV4G3++9bOcrVJ614KiF+jS66omKNdro4g5Z3dF5Dy/11JBKYlofCMJ84hQ63YUR1krTm12nHghLDXw3BSwik7Xrid+3TaRbeZiWyTz1BI4JQFMQjlO6Vf8UzY6pyPtms1c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
